import { hashSync } from 'bcrypt-ts'

const sampleData = {
  categories: [
    // ── Parent Categories (5) ──────────────────────────────────────
    {
      name: 'Γρανάζια ABS',
      slug: 'granazia-abs',
      description:
        'Γρανάζια αισθητήρων ABS για όλους τους τύπους επαγγελματικών οχημάτων',
      image: '/images/categories/granazia-abs.svg',
      parentSlug: null,
      sortOrder: 1,
    },
    {
      name: 'Ειδικές Κατασκευές',
      slug: 'eidikes-kataskeves',
      description:
        'Κατασκευές κατά παραγγελία σε CNC τόρνο και φρέζα — ορείχαλκος, ατσάλι, αλουμίνιο',
      image: '/images/categories/eidikes-kataskeves.svg',
      parentSlug: null,
      sortOrder: 2,
    },
    {
      name: 'Εξαρτήματα Αεροφρένων',
      slug: 'eksartimata-aerofrenwn',
      description:
        'Φυσούνες, σύνδεσμοι και εξαρτήματα αεροπέδησης για φορτηγά και ρυμουλκούμενα',
      image: '/images/categories/eksartimata-aerofrenwn.svg',
      parentSlug: null,
      sortOrder: 3,
    },
    {
      name: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      slug: 'eksartimata-swlinosewn',
      description:
        'Ρακόρ, μούφες, ουρές, αντιστάσεις και σωλήνες για υδραυλικά και πνευματικά φρένα',
      image: '/images/categories/eksartimata-swlinosewn.svg',
      parentSlug: null,
      sortOrder: 4,
    },
    {
      name: 'Κατασκευές Σωλήνων / Μαρκούτσια',
      slug: 'kataskeves-swlinwn',
      description:
        'Έτοιμα μαρκούτσια φρένων, Teflon και γρασσαδόρου σε διάφορα μήκη',
      image: '/images/categories/kataskeves-swlinwn.svg',
      parentSlug: null,
      sortOrder: 5,
    },

    // ── Subcategories: Γρανάζια ABS ────────────────────────────────
    {
      name: 'Γρανάζια DAF / MAN',
      slug: 'granazia-daf-man',
      description: 'Γρανάζια ABS για DAF CF, XF, MAN TGA, TGS, TGX',
      image: null,
      parentSlug: 'granazia-abs',
      sortOrder: 1,
    },
    {
      name: 'Γρανάζια Mercedes',
      slug: 'granazia-mercedes',
      description: 'Γρανάζια ABS για Mercedes Actros, Atego, Vario, Axor',
      image: null,
      parentSlug: 'granazia-abs',
      sortOrder: 2,
    },
    {
      name: 'Γρανάζια Volvo / Scania',
      slug: 'granazia-volvo-scania',
      description: 'Γρανάζια ABS για Volvo FH, FM, Scania R, P Series',
      image: null,
      parentSlug: 'granazia-abs',
      sortOrder: 3,
    },

    // ── Subcategories: Ειδικές Κατασκευές ──────────────────────────
    {
      name: 'Κατεργασία Τόρνου CNC',
      slug: 'katergasia-tornoy-cnc',
      description:
        'Κατασκευή εξαρτημάτων σε CNC τόρνο — δαχτυλίδια, άξονες, έμβολα',
      image: null,
      parentSlug: 'eidikes-kataskeves',
      sortOrder: 1,
    },
    {
      name: 'Κατεργασία Φρέζας CNC',
      slug: 'katergasia-frezas-cnc',
      description: 'Κατασκευή βάσεων, πλακών και φλαντζών σε CNC φρέζα',
      image: null,
      parentSlug: 'eidikes-kataskeves',
      sortOrder: 2,
    },

    // ── Subcategories: Εξαρτήματα Αεροφρένων ───────────────────────
    {
      name: 'Φυσούνες για Ταμπούρο',
      slug: 'fysoynes-tampouro',
      description:
        'Φυσούνες μονής και διπλής ενέργειας για ταμπούρο — πρεσσαριστές και ενισχυμένες',
      image: null,
      parentSlug: 'eksartimata-aerofrenwn',
      sortOrder: 1,
    },
    {
      name: 'Φυσούνες Δισκοφρένου',
      slug: 'fysoynes-diskofrenoy',
      description:
        'Φυσούνες διπλής ενέργειας για δισκόφρενα — AVL και SORL',
      image: null,
      parentSlug: 'eksartimata-aerofrenwn',
      sortOrder: 2,
    },
    {
      name: 'Αυτόματοι Σύνδεσμοι Αέρος',
      slug: 'aytomatoi-syndesmoi-aeros',
      description:
        'Push-in σύνδεσμοι πλαστικοί, μεταλλοπλαστικοί, μεταλλικοί και ορειχάλκινοι',
      image: null,
      parentSlug: 'eksartimata-aerofrenwn',
      sortOrder: 3,
    },

    // ── Subcategories: Εξαρτήματα Σωληνώσεων ──────────────────────
    {
      name: 'Ρακόρ Υδραυλικών Φρένων',
      slug: 'rakor-frenon',
      description:
        'Πρεσσαριστά ρακόρ, βίδες, λαδοβίδες, θηλιές και εξαερωτήρες φρένων',
      image: null,
      parentSlug: 'eksartimata-swlinosewn',
      sortOrder: 1,
    },
    {
      name: 'Αντιστάσεις & Σφήνες Σωλήνας',
      slug: 'antistaseis-solinas',
      description:
        'Πλαστικές σφήνες (αντιστάσεις) για σωλήνες αέρος φορτηγών — 15+ διαστάσεις',
      image: null,
      parentSlug: 'eksartimata-swlinosewn',
      sortOrder: 2,
    },
    {
      name: 'Ουρές, Μούφες & Τάπες',
      slug: 'oyres-moyfes-tapes',
      description:
        'Ουρές πλαστικής/ελαστικής σωλήνας, μούφες, τάπες, μαστοί, κυάθια',
      image: null,
      parentSlug: 'eksartimata-swlinosewn',
      sortOrder: 3,
    },
    {
      name: 'Σωλήνες & Λάστιχα',
      slug: 'solines-lastixa',
      description:
        'Σωλήνες πλαστικές, μεταλλικές εύκαμπτες, R6 λαδιού, Teflon, Flex',
      image: null,
      parentSlug: 'eksartimata-swlinosewn',
      sortOrder: 4,
    },

    // ── Subcategories: Κατασκευές Σωλήνων ──────────────────────────
    {
      name: 'Μαρκούτσια Teflon',
      slug: 'markoutsia-teflon',
      description:
        'Μαρκούτσια Teflon υψηλής θερμοκρασίας & πίεσης — σκληρά και εύκαμπτα',
      image: null,
      parentSlug: 'kataskeves-swlinwn',
      sortOrder: 1,
    },
    {
      name: 'Μαρκούτσια Φρένων & Αμπραγιάζ',
      slug: 'markoutsia-frenon',
      description:
        'Έτοιμα μαρκούτσια υδραυλικών φρένων, αμπραγιάζ και γρασσαδόρου',
      image: null,
      parentSlug: 'kataskeves-swlinwn',
      sortOrder: 2,
    },
  ],

  products: [
    // ═══════════════════════════════════════════════════════════════
    // ΓΡΑΝΆΖΙΑ ABS
    // ═══════════════════════════════════════════════════════════════

    // ── Γρανάζια DAF / MAN ─────────────────────────────────────────
    {
      name: 'Γρανάζι ABS 48 δοντιών DAF CF/XF',
      slug: 'granazi-abs-48-daf-cf-xf',
      category: 'Γρανάζια ABS',
      categorySlug: 'granazia-daf-man',
      description:
        'Γρανάζι αισθητήρα ABS 48 δοντιών για DAF CF και XF. Κατασκευή από ειδικό χάλυβα υψηλής αντοχής, συμβατό με αισθητήρες WABCO και Knorr-Bremse.',
      images: ['/images/placeholder.svg'],
      price: 45.0,
      brand: 'AVL',
      rating: 4.5,
      numReviews: 12,
      stock: 25,
      isFeatured: false,
      banner: null,
      specs: {
        teeth: 48,
        material: 'Special Steel',
        compatibleVehicles: ['DAF CF', 'DAF XF'],
        oem: 'WABCO / Knorr-Bremse compatible',
      },
    },
    {
      name: 'Γρανάζι ABS 48 δοντιών MAN TGA/TGS',
      slug: 'granazi-abs-48-man-tga-tgs',
      category: 'Γρανάζια ABS',
      categorySlug: 'granazia-daf-man',
      description:
        'Γρανάζι ABS 48 δοντιών για MAN TGA και TGS. Ακριβής κατεργασία CNC, ανθεκτικό σε θερμοκρασίες λειτουργίας φρένων.',
      images: ['/images/placeholder.svg'],
      price: 45.0,
      brand: 'AVL',
      rating: 4.3,
      numReviews: 8,
      stock: 20,
      isFeatured: false,
      banner: null,
      specs: {
        teeth: 48,
        material: 'Special Steel',
        compatibleVehicles: ['MAN TGA', 'MAN TGS'],
        oem: 'CNC machined',
      },
    },
    {
      name: 'Γρανάζι ABS 80 δοντιών MAN TGX',
      slug: 'granazi-abs-80-man-tgx',
      category: 'Γρανάζια ABS',
      categorySlug: 'granazia-daf-man',
      description:
        'Γρανάζι ABS 80 δοντιών για MAN TGX. Μεγαλύτερος αριθμός δοντιών για ακριβέστερη ανίχνευση ταχύτητας τροχού.',
      images: ['/images/placeholder.svg'],
      price: 58.0,
      brand: 'AVL',
      rating: 4.7,
      numReviews: 5,
      stock: 15,
      isFeatured: false,
      banner: null,
      specs: {
        teeth: 80,
        material: 'Special Steel',
        compatibleVehicles: ['MAN TGX'],
        oem: 'High-resolution speed detection',
      },
    },

    // ── Γρανάζια Mercedes ──────────────────────────────────────────
    {
      name: 'Γρανάζι ABS 100 δοντιών Mercedes Actros MP2/MP3',
      slug: 'granazi-abs-100-mercedes-actros',
      category: 'Γρανάζια ABS',
      categorySlug: 'granazia-mercedes',
      description:
        'Γρανάζι αισθητήρα ABS 100 δοντιών για Mercedes Actros MP2 και MP3. Υψηλή ακρίβεια κατεργασίας, πιστοποιημένο για EBS.',
      images: ['/images/placeholder.svg'],
      price: 62.0,
      brand: 'AVL',
      rating: 4.8,
      numReviews: 15,
      stock: 18,
      isFeatured: true,
      banner: '/images/banners/hero-abs-gears.svg',
      specs: {
        teeth: 100,
        material: 'Special Steel',
        compatibleVehicles: ['Mercedes Actros MP2', 'Mercedes Actros MP3'],
        oem: 'EBS certified',
      },
    },
    {
      name: 'Γρανάζι ABS 90 δοντιών Mercedes Atego',
      slug: 'granazi-abs-90-mercedes-atego',
      category: 'Γρανάζια ABS',
      categorySlug: 'granazia-mercedes',
      description:
        'Γρανάζι ABS 90 δοντιών για Mercedes Atego. Ιδανικό για αντικατάσταση — άμεση τοποθέτηση χωρίς τροποποιήσεις.',
      images: ['/images/placeholder.svg'],
      price: 55.0,
      brand: 'AVL',
      rating: 4.4,
      numReviews: 7,
      stock: 22,
      isFeatured: false,
      banner: null,
      specs: {
        teeth: 90,
        material: 'Special Steel',
        compatibleVehicles: ['Mercedes Atego'],
        oem: 'Direct fit replacement',
      },
    },
    {
      name: 'Γρανάζι ABS 80 δοντιών Mercedes Vario',
      slug: 'granazi-abs-80-mercedes-vario',
      category: 'Γρανάζια ABS',
      categorySlug: 'granazia-mercedes',
      description:
        'Γρανάζι ABS 80 δοντιών για Mercedes Vario. Κατασκευή AVL, εγγύηση ποιότητας και αντοχής.',
      images: ['/images/placeholder.svg'],
      price: 52.0,
      brand: 'AVL',
      rating: 4.2,
      numReviews: 4,
      stock: 12,
      isFeatured: false,
      banner: null,
      specs: {
        teeth: 80,
        material: 'Special Steel',
        compatibleVehicles: ['Mercedes Vario'],
        oem: 'AVL quality guaranteed',
      },
    },

    // ── Γρανάζια Volvo / Scania ───────────────────────────────────
    {
      name: 'Γρανάζι ABS 100 δοντιών Volvo FH/FM',
      slug: 'granazi-abs-100-volvo-fh-fm',
      category: 'Γρανάζια ABS',
      categorySlug: 'granazia-volvo-scania',
      description:
        'Γρανάζι αισθητήρα ABS 100 δοντιών για Volvo FH και FM. Premium ποιότητα, άριστη εφαρμογή.',
      images: ['/images/placeholder.svg'],
      price: 65.0,
      brand: 'AVL',
      rating: 4.6,
      numReviews: 9,
      stock: 14,
      isFeatured: false,
      banner: null,
      specs: {
        teeth: 100,
        material: 'Special Steel',
        compatibleVehicles: ['Volvo FH', 'Volvo FM'],
        oem: 'Premium quality fit',
      },
    },
    {
      name: 'Γρανάζι ABS 90 δοντιών Scania R/P',
      slug: 'granazi-abs-90-scania-r-p',
      category: 'Γρανάζια ABS',
      categorySlug: 'granazia-volvo-scania',
      description:
        'Γρανάζι ABS 90 δοντιών για Scania R και P Series. Κατεργασία CNC, ανθεκτικό σε κραδασμούς.',
      images: ['/images/placeholder.svg'],
      price: 62.0,
      brand: 'AVL',
      rating: 4.5,
      numReviews: 6,
      stock: 16,
      isFeatured: false,
      banner: null,
      specs: {
        teeth: 90,
        material: 'Special Steel',
        compatibleVehicles: ['Scania R Series', 'Scania P Series'],
        oem: 'CNC machined, vibration resistant',
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // ΕΙΔΙΚΈΣ ΚΑΤΑΣΚΕΥΈΣ CNC
    // ═══════════════════════════════════════════════════════════════

    // ── Κατεργασία Τόρνου CNC ──────────────────────────────────────
    {
      name: 'Μπρούτζινο δαχτυλίδι θαλάμου φρένων CNC',
      slug: 'mproutzino-daxtylidi-thalamou-cnc',
      category: 'Ειδικές Κατασκευές',
      categorySlug: 'katergasia-tornoy-cnc',
      description:
        'Δαχτυλίδι ορειχάλκου κατασκευασμένο σε CNC τόρνο. Κατά παραγγελία σε οποιαδήποτε διάσταση. Ιδανικό για θαλάμους φρένων και πνευματικά συστήματα.',
      images: ['/images/placeholder.svg'],
      price: 35.0,
      brand: 'AVL',
      rating: 4.9,
      numReviews: 3,
      stock: 50,
      isFeatured: false,
      banner: null,
      specs: {
        material: 'Brass',
        tolerance: '±0.02mm',
        process: 'CNC Lathe',
      },
    },
    {
      name: 'Ατσάλινος άξονας φρένων CNC',
      slug: 'atsalinos-axonas-frenon-cnc',
      category: 'Ειδικές Κατασκευές',
      categorySlug: 'katergasia-tornoy-cnc',
      description:
        'Άξονας από ειδικό χάλυβα για μηχανισμούς φρένων. Κατεργασία CNC υψηλής ακρίβειας (±0.01mm).',
      images: ['/images/placeholder.svg'],
      price: 85.0,
      brand: 'AVL',
      rating: 5.0,
      numReviews: 2,
      stock: 30,
      isFeatured: false,
      banner: null,
      specs: {
        material: 'Steel',
        tolerance: '±0.01mm',
        process: 'CNC Lathe',
      },
    },
    {
      name: 'Αλουμινένιο έμβολο θαλάμου φρένων CNC',
      slug: 'alouminenio-emvolo-thalamou-cnc',
      category: 'Ειδικές Κατασκευές',
      categorySlug: 'katergasia-tornoy-cnc',
      description:
        'Έμβολο αλουμινίου για θαλάμους φρένων. Ελαφρύ, ανθεκτικό στη διάβρωση. Κατεργασία σε CNC τόρνο με ανοχές ±0.02mm.',
      images: ['/images/placeholder.svg'],
      price: 120.0,
      brand: 'AVL',
      rating: 4.8,
      numReviews: 4,
      stock: 20,
      isFeatured: false,
      banner: null,
      specs: {
        material: 'Aluminum',
        tolerance: '±0.02mm',
        process: 'CNC Lathe',
      },
    },

    // ── Κατεργασία Φρέζας CNC ──────────────────────────────────────
    {
      name: 'Βάση στήριξης δαγκάνας φρένων CNC',
      slug: 'vasi-stirixis-dagkanas-cnc',
      category: 'Ειδικές Κατασκευές',
      categorySlug: 'katergasia-frezas-cnc',
      description:
        'Βάση στήριξης δαγκάνας κατεργασμένη σε CNC φρέζα. Ατσάλι υψηλής αντοχής, για δισκόφρενα φορτηγών.',
      images: ['/images/placeholder.svg'],
      price: 95.0,
      brand: 'AVL',
      rating: 4.7,
      numReviews: 3,
      stock: 15,
      isFeatured: false,
      banner: null,
      specs: {
        material: 'Steel',
        tolerance: '±0.01mm',
        process: 'CNC Milling',
      },
    },
    {
      name: 'Φλάντζα σύνδεσης κομπρεσέρ CNC',
      slug: 'flantza-syndesis-kompreser-cnc',
      category: 'Ειδικές Κατασκευές',
      categorySlug: 'katergasia-frezas-cnc',
      description:
        'Φλάντζα αλουμινίου για σύνδεση κομπρεσέρ αέρος. Κατεργασία CNC φρέζα, ακριβής επιφάνεια στεγανοποίησης.',
      images: ['/images/placeholder.svg'],
      price: 110.0,
      brand: 'AVL',
      rating: 4.6,
      numReviews: 2,
      stock: 10,
      isFeatured: true,
      banner: '/images/banners/hero-cnc.svg',
      specs: {
        material: 'Aluminum',
        tolerance: '±0.01mm',
        process: 'CNC Milling',
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // ΕΞΑΡΤΉΜΑΤΑ ΑΕΡΟΦΡΈΝΩΝ — ΦΥΣΟΎΝΕΣ ΓΙΑ ΤΑΜΠΟΎΡΟ
    // ═══════════════════════════════════════════════════════════════
    {
      name: 'Φυσούνες Μ.Ε. για ταμπούρο T12',
      slug: 'fysoynes-me-tampouro-t12-fa1012a',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'fysoynes-tampouro',
      description:
        'Φυσούνα μονής ενέργειας T12 για ταμπούρο. Κωδικός AVL: FA1012A. Κατάλληλη για θαλάμους τύπου 12, εγκατάσταση plug & play.',
      images: ['/images/placeholder.svg'],
      price: 8.5,
      brand: 'AVL',
      rating: 4.4,
      numReviews: 18,
      stock: 100,
      isFeatured: false,
      banner: null,
      specs: {
        type: 'Single Acting',
        size: 'T12',
        tempRange: '-40°C to +80°C',
        avlCode: 'FA1012A',
      },
    },
    {
      name: 'Φυσούνες Δ.Ε. για ταμπούρο T24',
      slug: 'fysoynes-de-tampouro-t24-fa1034a',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'fysoynes-tampouro',
      description:
        'Φυσούνα διπλής ενέργειας T24 για ταμπούρο. Κωδικός AVL: FA1034A. Υψηλής αντοχής ελαστικό, θερμοκρασίες -40°C έως +80°C.',
      images: ['/images/products/fa1034a/01.png'],
      price: 12.0,
      brand: 'AVL',
      rating: 4.6,
      numReviews: 22,
      stock: 80,
      isFeatured: false,
      banner: null,
      specs: {
        type: 'Double Acting',
        size: 'T24',
        tempRange: '-40°C to +80°C',
        avlCode: 'FA1034A',
      },
    },
    {
      name: 'Πρεσσαριστές φυσούνες Δ.Ε. ταμπούρο T24',
      slug: 'pressaristes-fysoynes-de-tampouro-t24-fa1078c',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'fysoynes-tampouro',
      description:
        'Πρεσσαριστή φυσούνα Δ.Ε. T24 για ταμπούρο. Κωδικός AVL: FA1078C. Μεταλλικό στεφάνι πρεσσαρισμένο για αυξημένη στεγανότητα.',
      images: ['/images/products/fa1078c/01.png'],
      price: 14.5,
      brand: 'AVL',
      rating: 4.5,
      numReviews: 14,
      stock: 60,
      isFeatured: false,
      banner: null,
      specs: {
        type: 'Double Acting',
        size: 'T24',
        tempRange: '-40°C to +80°C',
        avlCode: 'FA1078C',
      },
    },
    {
      name: 'Ενισχυμένες φυσούνες Δ.Ε. ταμπούρο T24',
      slug: 'enisxymenes-fysoynes-de-tampouro-t24-fa1032a',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'fysoynes-tampouro',
      description:
        'Ενισχυμένη φυσούνα Δ.Ε. T24 για ταμπούρο. Κωδικός AVL: FA1032A. Διπλό ύφασμα ενίσχυσης, μεγάλη διάρκεια ζωής.',
      images: ['/images/products/fa1032a/01.png'],
      price: 16.0,
      brand: 'AVL',
      rating: 4.7,
      numReviews: 16,
      stock: 45,
      isFeatured: false,
      banner: null,
      specs: {
        type: 'Double Acting',
        size: 'T24',
        tempRange: '-40°C to +80°C',
        avlCode: 'FA1032A',
      },
    },
    {
      name: 'Φυσούνες με διπλά στεφάνια και άξονα',
      slug: 'fysoynes-dipla-stefania-axona-fa1026a',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'fysoynes-tampouro',
      description:
        'Φυσούνα με διπλά μεταλλικά στεφάνια και ενσωματωμένο άξονα. Κωδικός AVL: FA1026A. Για βαρέα οχήματα.',
      images: ['/images/products/fa1026a/01.png'],
      price: 18.5,
      brand: 'AVL',
      rating: 4.3,
      numReviews: 9,
      stock: 35,
      isFeatured: false,
      banner: null,
      specs: {
        type: 'Double Acting',
        size: 'T24',
        tempRange: '-40°C to +80°C',
        avlCode: 'FA1026A',
      },
    },
    {
      name: 'Φυσούνες με σπείρωμα M16',
      slug: 'fysoynes-speiroma-m16-fa1043d',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'fysoynes-tampouro',
      description:
        'Φυσούνα με σπείρωμα M16 για ειδικές εφαρμογές. Κωδικός AVL: FA1043D. Σύνδεση απευθείας σε σώμα θαλάμου.',
      images: ['/images/products/fa1043d/01.png'],
      price: 15.0,
      brand: 'AVL',
      rating: 4.1,
      numReviews: 6,
      stock: 40,
      isFeatured: false,
      banner: null,
      specs: {
        type: 'Single Acting',
        size: 'T16',
        tempRange: '-40°C to +80°C',
        avlCode: 'FA1043D',
        threadSize: 'M16',
      },
    },
    {
      name: 'Φυσούνες Μ.Ε. ενισχυμένες T12',
      slug: 'fysoynes-me-enisxymenes-t12-fa1055a',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'fysoynes-tampouro',
      description:
        'Ενισχυμένη φυσούνα μονής ενέργειας T12. Κωδικός AVL: FA1055A. Με ενίσχυση υφάσματος για αυξημένη αντοχή σε πίεση.',
      images: ['/images/placeholder.svg'],
      price: 11.0,
      brand: 'AVL',
      rating: 4.2,
      numReviews: 7,
      stock: 55,
      isFeatured: false,
      banner: null,
      specs: {
        type: 'Single Acting',
        size: 'T12',
        tempRange: '-40°C to +80°C',
        avlCode: 'FA1055A',
      },
    },
    {
      name: 'Φυσούνες Δ.Ε. πρεσσαριστές ενισχυμένες T30',
      slug: 'fysoynes-de-pressaristes-enisxymenes-t30-fa1060b',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'fysoynes-tampouro',
      description:
        'Πρεσσαριστή ενισχυμένη φυσούνα Δ.Ε. T30 για βαρέα φορτηγά. Κωδικός AVL: FA1060B. Μέγιστη πίεση λειτουργίας 10 bar.',
      images: ['/images/placeholder.svg'],
      price: 22.0,
      brand: 'AVL',
      rating: 4.8,
      numReviews: 4,
      stock: 25,
      isFeatured: true,
      banner: '/images/banners/hero-air-brakes.svg',
      specs: {
        type: 'Double Acting',
        size: 'T30',
        tempRange: '-40°C to +80°C',
        maxPressure: '10 bar',
        avlCode: 'FA1060B',
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // ΕΞΑΡΤΉΜΑΤΑ ΑΕΡΟΦΡΈΝΩΝ — ΦΥΣΟΎΝΕΣ ΔΙΣΚΟΦΡΈΝΟΥ
    // ═══════════════════════════════════════════════════════════════
    {
      name: 'Φυσούνες Μ.Ε. δισκοφρένου',
      slug: 'fysoynes-me-diskofrenoy-fa1021b',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'fysoynes-diskofrenoy',
      description:
        'Φυσούνα μονής ενέργειας για δισκόφρενα. Κωδικός AVL: FA1021B. Σχεδιασμένη για τα σύγχρονα δισκόφρενα φορτηγών.',
      images: ['/images/products/fa1021b/01.png'],
      price: 10.5,
      brand: 'AVL',
      rating: 4.5,
      numReviews: 11,
      stock: 70,
      isFeatured: false,
      banner: null,
      specs: {
        type: 'Single Acting',
        size: 'T16',
        tempRange: '-40°C to +80°C',
        avlCode: 'FA1021B',
      },
    },
    {
      name: 'Φυσούνες Δ.Ε. δισκοφρένου T16/24',
      slug: 'fysoynes-de-diskofrenoy-t16-24-fa1065b',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'fysoynes-diskofrenoy',
      description:
        'Φυσούνα διπλής ενέργειας T16/24 για δισκόφρενα. Κωδικός AVL: FA1065B. Η δημοφιλέστερη φυσούνα δισκοφρένου.',
      images: ['/images/products/fa1065b/01.png'],
      price: 14.0,
      brand: 'AVL',
      rating: 4.7,
      numReviews: 25,
      stock: 90,
      isFeatured: true,
      banner: '/images/banners/hero-fittings.svg',
      specs: {
        type: 'Double Acting',
        size: 'T16/24',
        tempRange: '-40°C to +80°C',
        avlCode: 'FA1065B',
      },
    },
    {
      name: 'Ενισχυμένες φυσούνες Δ.Ε. δισκοφρένου',
      slug: 'enisxymenes-fysoynes-de-diskofrenoy-fa1090a',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'fysoynes-diskofrenoy',
      description:
        'Ενισχυμένη φυσούνα Δ.Ε. για δισκόφρενα. Κωδικός AVL: FA1090A. Ενισχυμένο ελαστικό με διπλό ύφασμα.',
      images: ['/images/products/fa1090a/01.png'],
      price: 18.0,
      brand: 'AVL',
      rating: 4.6,
      numReviews: 13,
      stock: 40,
      isFeatured: false,
      banner: null,
      specs: {
        type: 'Double Acting',
        size: 'T24',
        tempRange: '-40°C to +80°C',
        avlCode: 'FA1090A',
      },
    },
    {
      name: 'Φυσούνες με διπλά στεφάνια δισκοφρένου',
      slug: 'fysoynes-dipla-stefania-diskofrenoy-fa1037a',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'fysoynes-diskofrenoy',
      description:
        'Φυσούνα με διπλά μεταλλικά στεφάνια για δισκόφρενα. Κωδικός AVL: FA1037A. Εξαιρετική στεγανότητα.',
      images: ['/images/products/fa1037a/01.png'],
      price: 20.0,
      brand: 'AVL',
      rating: 4.4,
      numReviews: 8,
      stock: 30,
      isFeatured: false,
      banner: null,
      specs: {
        type: 'Double Acting',
        size: 'T24',
        tempRange: '-40°C to +80°C',
        avlCode: 'FA1037A',
      },
    },
    {
      name: 'Φυσούνες Δ.Ε. Δισκοφρένου SORL DAF/MAN 12/16',
      slug: 'fysoynes-de-diskofrenoy-sorl-daf-man-35306300050',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'fysoynes-diskofrenoy',
      description:
        'Φυσούνα Δ.Ε. δισκοφρένου SORL για DAF και MAN 12/16. Κωδικός: 35306300050. OEM ποιότητα, ανταγωνιστική τιμή.',
      images: ['/images/placeholder.svg'],
      price: 22.5,
      brand: 'SORL',
      rating: 4.3,
      numReviews: 10,
      stock: 35,
      isFeatured: false,
      banner: null,
      specs: {
        type: 'Double Acting',
        size: 'T12/16',
        tempRange: '-40°C to +80°C',
        avlCode: '35306300050',
        compatibleVehicles: ['DAF', 'MAN'],
      },
    },
    {
      name: 'Φυσούνες Δ.Ε. Δισκοφρένου SORL αλουμινίου',
      slug: 'fysoynes-de-diskofrenoy-sorl-alouminioy-35303901710',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'fysoynes-diskofrenoy',
      description:
        'Φυσούνα Δ.Ε. δισκοφρένου SORL με αλουμινένιο στεφάνι. Κωδικός: 35303901710. Ελαφρύτερη, ανθεκτική στη διάβρωση.',
      images: ['/images/products/35303901710/01.png'],
      price: 28.0,
      brand: 'SORL',
      rating: 4.5,
      numReviews: 7,
      stock: 20,
      isFeatured: false,
      banner: null,
      specs: {
        type: 'Double Acting',
        size: 'T24',
        tempRange: '-40°C to +80°C',
        avlCode: '35303901710',
      },
    },
    {
      name: 'Φυσούνα MS Vario/Atego SORL',
      slug: 'fysoyna-ms-vario-atego-sorl-35195700030',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'fysoynes-diskofrenoy',
      description:
        'Φυσούνα SORL για Mercedes Vario και Atego. Κωδικός: 35195700030. Απευθείας αντικατάσταση γνήσιου.',
      images: ['/images/placeholder.svg'],
      price: 25.0,
      brand: 'SORL',
      rating: 4.4,
      numReviews: 6,
      stock: 18,
      isFeatured: false,
      banner: null,
      specs: {
        type: 'Single Acting',
        size: 'T16',
        tempRange: '-40°C to +80°C',
        avlCode: '35195700030',
        compatibleVehicles: ['Mercedes Vario', 'Mercedes Atego'],
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // ΕΞΑΡΤΉΜΑΤΑ ΑΕΡΟΦΡΈΝΩΝ — ΑΥΤΌΜΑΤΟΙ ΣΎΝΔΕΣΜΟΙ ΑΈΡΟΣ
    // ═══════════════════════════════════════════════════════════════
    {
      name: 'Γωνία Α-Θ αυτόματη 6mm',
      slug: 'gonia-a-th-aytomati-6mm-ef0310601',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'aytomatoi-syndesmoi-aeros',
      description:
        'Αυτόματος σύνδεσμος γωνία αρσενικό-θηλυκό 6mm. Κωδικός: EF0310601. Push-in τεχνολογία, εύκολη σύνδεση/αποσύνδεση.',
      images: ['/images/products/0310601/01.png'],
      price: 2.6,
      brand: 'Camozzi',
      rating: 4.3,
      numReviews: 15,
      stock: 200,
      isFeatured: false,
      banner: null,
      specs: {
        connectionType: 'Push-in',
        tubeSize: '6mm',
        material: 'Plastic',
        maxPressure: '15 bar',
      },
    },
    {
      name: 'Ταφ Α-Θ-Α αυτόματο 6mm',
      slug: 'taf-a-th-a-aytomato-6mm-tf0330601',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'aytomatoi-syndesmoi-aeros',
      description:
        'Αυτόματος σύνδεσμος ταφ Α-Θ-Α (τρελλό στη μέση) 6mm. Κωδικός: TF0330601. Πλήρως αεροστεγής σύνδεση.',
      images: ['/images/products/0330601/01.png'],
      price: 3.88,
      brand: 'Camozzi',
      rating: 4.2,
      numReviews: 12,
      stock: 150,
      isFeatured: false,
      banner: null,
      specs: {
        connectionType: 'Push-in',
        tubeSize: '6mm',
        material: 'Plastic',
        maxPressure: '15 bar',
      },
    },
    {
      name: 'Ταφ Θ-Α-Θ αυτόματο 6mm',
      slug: 'taf-th-a-th-aytomato-6mm-tf0340601',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'aytomatoi-syndesmoi-aeros',
      description:
        'Αυτόματος σύνδεσμος ταφ Θ-Α-Θ (τρελλό στην άκρη) 6mm. Κωδικός: TF0340601. Στεγανοποίηση με O-ring.',
      images: ['/images/products/0340601/01.png'],
      price: 3.88,
      brand: 'Camozzi',
      rating: 4.1,
      numReviews: 10,
      stock: 150,
      isFeatured: false,
      banner: null,
      specs: {
        connectionType: 'Push-in',
        tubeSize: '6mm',
        material: 'Plastic',
        maxPressure: '15 bar',
      },
    },
    {
      name: 'Ταφ στη μέση κόντρα αρσενικό M18x22',
      slug: 'taf-mesi-kontra-arseniko-m18x22-tf0441822',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'aytomatoi-syndesmoi-aeros',
      description:
        'Αυτόματος σύνδεσμος ταφ στη μέση κόντρα (αρσενικό). Κωδικός: TF0441822. Σπείρωμα M18x22.',
      images: ['/images/products/0441822/01.png'],
      price: 3.7,
      brand: 'Camozzi',
      rating: 4.0,
      numReviews: 8,
      stock: 120,
      isFeatured: false,
      banner: null,
      specs: {
        connectionType: 'Push-in',
        tubeSize: '6mm',
        threadSize: 'M18x22',
        material: 'Metal-Plastic',
        maxPressure: '15 bar',
      },
    },
    {
      name: 'Σύνδεσμος πλαστικός αυτόματος υψιλον',
      slug: 'syndesmos-plastikos-aytomatos-ypsilon-pp12304',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'aytomatoi-syndesmoi-aeros',
      description:
        'Πλαστικός αυτόματος σύνδεσμος υψιλον (Y). Κωδικός: PP12304. Ελαφρύς, ανθεκτικός στη διάβρωση.',
      images: ['/images/placeholder.svg'],
      price: 0.62,
      brand: 'Camozzi',
      rating: 4.0,
      numReviews: 20,
      stock: 300,
      isFeatured: false,
      banner: null,
      specs: {
        connectionType: 'Push-in',
        tubeSize: '4mm',
        material: 'Plastic',
      },
    },
    {
      name: 'Σύνδεσμος βάσεως NPT μεταλλοπλαστικός ίσιος',
      slug: 'syndesmos-vaseos-npt-metalloplastikos-isios-pm1250618',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'aytomatoi-syndesmoi-aeros',
      description:
        'Μεταλλοπλαστικός σύνδεσμος βάσεως NPT ίσιος. Κωδικός: PM1250618. Σπείρωμα NPT 6mm, σωλήνα 18mm.',
      images: ['/images/products/1250618/01.png'],
      price: 0.62,
      brand: 'Camozzi',
      rating: 4.1,
      numReviews: 14,
      stock: 250,
      isFeatured: false,
      banner: null,
      specs: {
        connectionType: 'Push-in',
        tubeSize: '6mm',
        threadSize: 'NPT 18mm',
        material: 'Metal-Plastic',
      },
    },
    {
      name: 'Σύνδεσμος βάσεως NPT μεταλλοπλαστικός γωνία',
      slug: 'syndesmos-vaseos-npt-metalloplastikos-gonia-pm1260618',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'aytomatoi-syndesmoi-aeros',
      description:
        'Μεταλλοπλαστικός σύνδεσμος βάσεως NPT γωνία. Κωδικός: PM1260618. Push-in σύνδεση 6mm, σπείρωμα 18mm.',
      images: ['/images/products/1260618/01.png'],
      price: 0.78,
      brand: 'Camozzi',
      rating: 4.2,
      numReviews: 11,
      stock: 200,
      isFeatured: false,
      banner: null,
      specs: {
        connectionType: 'Push-in',
        tubeSize: '6mm',
        threadSize: 'NPT 18mm',
        material: 'Metal-Plastic',
      },
    },
    {
      name: 'Σύνδεσμος μεταλλικός αυτόματος ίσιος 4mm',
      slug: 'syndesmos-metallikos-aytomatos-isios-4mm-pf13204',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'aytomatoi-syndesmoi-aeros',
      description:
        'Μεταλλικός αυτόματος σύνδεσμος ίσιος 4mm. Κωδικός: PF13204. Νικελαρισμένος ορείχαλκος, πίεση λειτ. 15 bar.',
      images: ['/images/placeholder.svg'],
      price: 2.47,
      brand: 'Camozzi',
      rating: 4.4,
      numReviews: 9,
      stock: 180,
      isFeatured: false,
      banner: null,
      specs: {
        connectionType: 'Push-in',
        tubeSize: '4mm',
        material: 'Metal',
        maxPressure: '15 bar',
      },
    },
    {
      name: 'Σύνδεσμος μεταλλικός αυτόματος γωνία 4mm',
      slug: 'syndesmos-metallikos-aytomatos-gonia-4mm-pf13304',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'aytomatoi-syndesmoi-aeros',
      description:
        'Μεταλλικός αυτόματος σύνδεσμος γωνία 4mm. Κωδικός: PF13304. Νικελαρισμένος ορείχαλκος.',
      images: ['/images/placeholder.svg'],
      price: 1.8,
      brand: 'Camozzi',
      rating: 4.3,
      numReviews: 7,
      stock: 160,
      isFeatured: false,
      banner: null,
      specs: {
        connectionType: 'Push-in',
        tubeSize: '4mm',
        material: 'Metal',
        maxPressure: '15 bar',
      },
    },
    {
      name: 'Σύνδεσμος μεταλλικός αυτόματος ταφ 4mm',
      slug: 'syndesmos-metallikos-aytomatos-taf-4mm-pf13404',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'aytomatoi-syndesmoi-aeros',
      description:
        'Μεταλλικός αυτόματος σύνδεσμος ταφ 4mm. Κωδικός: PF13404. Τριπλή διακλάδωση αέρος.',
      images: ['/images/placeholder.svg'],
      price: 3.46,
      brand: 'Camozzi',
      rating: 4.2,
      numReviews: 6,
      stock: 140,
      isFeatured: false,
      banner: null,
      specs: {
        connectionType: 'Push-in',
        tubeSize: '4mm',
        material: 'Metal',
        maxPressure: '15 bar',
      },
    },
    {
      name: 'Σύνδεσμος βάσεως BSP μεταλλικός 6/12mm',
      slug: 'syndesmos-vaseos-bsp-metallikos-6-12mm-pf1350612',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'aytomatoi-syndesmoi-aeros',
      description:
        'Μεταλλικός σύνδεσμος βάσεως BSP 6mm σωλήνα, 12mm σπείρωμα. Κωδικός: PF1350612.',
      images: ['/images/placeholder.svg'],
      price: 2.53,
      brand: 'Camozzi',
      rating: 4.3,
      numReviews: 5,
      stock: 130,
      isFeatured: false,
      banner: null,
      specs: {
        connectionType: 'Push-in',
        tubeSize: '6mm',
        threadSize: 'BSP 12mm',
        material: 'Metal',
        maxPressure: '15 bar',
      },
    },
    {
      name: 'Σύνδεσμος βάσεως NPT μεταλλικός 4/18mm',
      slug: 'syndesmos-vaseos-npt-metallikos-4-18mm-pf1360418',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'aytomatoi-syndesmoi-aeros',
      description:
        'Μεταλλικός σύνδεσμος βάσεως NPT 4mm σωλήνα, 18mm σπείρωμα. Κωδικός: PF1360418.',
      images: ['/images/products/1360418/01.png'],
      price: 1.31,
      brand: 'Camozzi',
      rating: 4.1,
      numReviews: 4,
      stock: 170,
      isFeatured: false,
      banner: null,
      specs: {
        connectionType: 'Push-in',
        tubeSize: '4mm',
        threadSize: 'NPT 18mm',
        material: 'Metal',
        maxPressure: '15 bar',
      },
    },
    {
      name: 'Σύνδεσμος βάσεως BSP γωνία μεταλλικός 6/12mm',
      slug: 'syndesmos-vaseos-bsp-gonia-metallikos-6-12mm-pf1370612',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'aytomatoi-syndesmoi-aeros',
      description:
        'Μεταλλικός σύνδεσμος βάσεως BSP γωνία 6mm σωλήνα, 12mm σπείρωμα. Κωδικός: PF1370612.',
      images: ['/images/placeholder.svg'],
      price: 3.89,
      brand: 'Camozzi',
      rating: 4.2,
      numReviews: 3,
      stock: 110,
      isFeatured: false,
      banner: null,
      specs: {
        connectionType: 'Push-in',
        tubeSize: '6mm',
        threadSize: 'BSP 12mm',
        material: 'Metal',
        maxPressure: '15 bar',
      },
    },
    {
      name: 'Σύνδεσμος βάσεως NPT γωνία μεταλλικός 4/18mm',
      slug: 'syndesmos-vaseos-npt-gonia-metallikos-4-18mm-pf1380418',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'aytomatoi-syndesmoi-aeros',
      description:
        'Μεταλλικός σύνδεσμος βάσεως NPT γωνία 4mm σωλήνα, 18mm σπείρωμα. Κωδικός: PF1380418.',
      images: ['/images/products/1380418/01.png'],
      price: 2.48,
      brand: 'Camozzi',
      rating: 4.0,
      numReviews: 5,
      stock: 120,
      isFeatured: false,
      banner: null,
      specs: {
        connectionType: 'Push-in',
        tubeSize: '4mm',
        threadSize: 'NPT 18mm',
        material: 'Metal',
        maxPressure: '15 bar',
      },
    },
    {
      name: 'Σύνδεσμος ορειχάλκινος ασφαλείας για οχήματα 6/4mm',
      slug: 'syndesmos-oreixalkinos-asfaleias-6-4mm-pb2050604',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'aytomatoi-syndesmoi-aeros',
      description:
        'Αυτόματος ορειχάλκινος σύνδεσμος ασφαλείας για οχήματα. Κωδικός: PB2050604. DOT πιστοποίηση.',
      images: ['/images/products/2050604/01.png'],
      price: 3.5,
      brand: 'Camozzi',
      rating: 4.6,
      numReviews: 8,
      stock: 100,
      isFeatured: false,
      banner: null,
      specs: {
        connectionType: 'Push-in',
        tubeSize: '6mm',
        material: 'Brass',
        maxPressure: '15 bar',
      },
    },
    {
      name: 'Σύνδεσμος ορειχάλκινος θηλυκό σπείρωμα 12/64mm',
      slug: 'syndesmos-oreixalkinos-thyliko-12-64mm-pb2201264',
      category: 'Εξαρτήματα Αεροφρένων',
      categorySlug: 'aytomatoi-syndesmoi-aeros',
      description:
        'Αυτόματος ορειχάλκινος σύνδεσμος με θηλυκό σπείρωμα 12mm/64mm. Κωδικός: PB2201264. Βαρέος τύπου.',
      images: ['/images/products/2201264/01.png'],
      price: 100.0,
      brand: 'Camozzi',
      rating: 4.7,
      numReviews: 2,
      stock: 8,
      isFeatured: false,
      banner: null,
      specs: {
        connectionType: 'Push-in',
        tubeSize: '12mm',
        threadSize: '64mm',
        material: 'Brass',
        maxPressure: '15 bar',
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // ΕΞΑΡΤΉΜΑΤΑ ΣΩΛΗΝΏΣΕΩΝ — ΡΑΚΌΡ ΦΡΈΝΩΝ
    // ═══════════════════════════════════════════════════════════════
    {
      name: 'Ρακόρ πρεσσαριστά 3/16" R1AT',
      slug: 'rakor-pressarista-3-16-r1at-hb041001ae',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'rakor-frenon',
      description:
        'Πρεσσαριστό ρακόρ 3/16" για σωλήνα R1AT. Κωδικός: HB-041001AE. Χαλύβδινο, με αντιδιαβρωτική επίστρωση.',
      images: ['/images/placeholder.svg'],
      price: 3.0,
      brand: 'AVL',
      rating: 4.3,
      numReviews: 12,
      stock: 200,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: '3/16"',
        material: 'Steel',
        connectionType: 'Crimp fitting',
      },
    },
    {
      name: 'Ρακόρ πρεσσαριστά 1/8" Teflon',
      slug: 'rakor-pressarista-1-8-teflon-hb091001ae',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'rakor-frenon',
      description:
        'Πρεσσαριστό ρακόρ 1/8" για σωλήνα Teflon. Κωδικός: HB-091001AE. Ανοξείδωτο, για υψηλές θερμοκρασίες.',
      images: ['/images/placeholder.svg'],
      price: 3.0,
      brand: 'AVL',
      rating: 4.4,
      numReviews: 8,
      stock: 150,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: '1/8"',
        material: 'Stainless',
        connectionType: 'Crimp fitting for Teflon hose',
      },
    },
    {
      name: 'Ρακόρ βίδα για θηλιά φρένων',
      slug: 'rakor-vida-gia-thilia-frenon-ba030601',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'rakor-frenon',
      description:
        'Βίδα ρακόρ για θηλιά φρένων M6. Κωδικός: BA030601. Χαλκός με νικέλιο.',
      images: ['/images/products/030601/01.png'],
      price: 0.58,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 20,
      stock: 500,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: 'M6',
        material: 'Brass',
        connectionType: 'Banjo bolt',
      },
    },
    {
      name: 'Λαδοβίδα διπλή M6',
      slug: 'ladovida-dipli-m6-ba060601',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'rakor-frenon',
      description:
        'Διπλή λαδοβίδα M6 για σύνδεση σωλήνων φρένων. Κωδικός: BA060601. Ορείχαλκος υψηλής ποιότητας.',
      images: ['/images/products/060601/01.png'],
      price: 2.06,
      brand: 'AVL',
      rating: 4.2,
      numReviews: 14,
      stock: 300,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: 'M6',
        material: 'Brass',
        connectionType: 'Double banjo bolt',
      },
    },
    {
      name: 'Θηλιές αέρος πλαστικής σωλήνας 8/6mm',
      slug: 'thilies-aeros-plastikis-solinas-8-6mm-ba020806',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'rakor-frenon',
      description:
        'Θηλιά αέρος για πλαστική σωλήνα 8x6mm. Κωδικός: BA020806. Ορειχάλκινη, σπείρωμα BSP.',
      images: ['/images/products/020806/01.png'],
      price: 3.4,
      brand: 'AVL',
      rating: 4.1,
      numReviews: 16,
      stock: 250,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: 'BSP',
        material: 'Brass',
        connectionType: 'Hose barb',
        tubeSize: '8x6mm',
      },
    },
    {
      name: 'Θηλιές ελαστικής σωλήνας 6/31mm',
      slug: 'thilies-elastikis-solinas-6-31mm-ba040631',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'rakor-frenon',
      description:
        'Θηλιά για ελαστική σωλήνα 6mm, σπείρωμα 31mm. Κωδικός: BA040631.',
      images: ['/images/products/040631/01.png'],
      price: 1.2,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 10,
      stock: 200,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: '31mm',
        material: 'Brass',
        connectionType: 'Hose barb',
        tubeSize: '6mm',
      },
    },
    {
      name: 'Ταφ υδραυλικών φρένων',
      slug: 'taf-ydravlikon-frenon-hb051001b',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'rakor-frenon',
      description:
        'Ταφ (T-piece) υδραυλικών φρένων. Κωδικός: HB051001B. Τριπλή διακλάδωση υγρών φρένων.',
      images: ['/images/products/hb051001b/01.png'],
      price: 7.75,
      brand: 'AVL',
      rating: 4.5,
      numReviews: 9,
      stock: 80,
      isFeatured: false,
      banner: null,
      specs: {
        material: 'Steel',
        connectionType: 'T-piece (3-way)',
      },
    },
    {
      name: 'Σταυροί υδραυλικών φρένων',
      slug: 'stavroi-ydravlikon-frenon-hb071001b',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'rakor-frenon',
      description:
        'Σταυρός (cross-piece) υδραυλικών φρένων. Κωδικός: HB071001B. Τετραπλή διακλάδωση.',
      images: ['/images/products/hb071001b/01.png'],
      price: 8.7,
      brand: 'AVL',
      rating: 4.4,
      numReviews: 6,
      stock: 60,
      isFeatured: false,
      banner: null,
      specs: {
        material: 'Steel',
        connectionType: 'Cross-piece (4-way)',
      },
    },
    {
      name: 'Εξαερωτήρες φρένων M6',
      slug: 'eksaerotires-frenon-m6-hb080601',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'rakor-frenon',
      description:
        'Εξαερωτήρας (bleeder) υδραυλικών φρένων M6. Κωδικός: HB080601. Για εξαέρωση κυκλώματος φρένων.',
      images: ['/images/products/080601/01.png'],
      price: 1.4,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 18,
      stock: 400,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: 'M6',
        material: 'Steel',
        connectionType: 'Bleeder valve',
      },
    },
    {
      name: 'Βαλβίδα καζανιού',
      slug: 'valvida-kazanioy-bk22',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'rakor-frenon',
      description:
        'Βαλβίδα εκκένωσης καζανιού αέρος. Κωδικός: BK22. Μηχανική, τραβηχτή. Ορείχαλκος.',
      images: ['/images/placeholder.svg'],
      price: 3.88,
      brand: 'AVL',
      rating: 4.3,
      numReviews: 11,
      stock: 100,
      isFeatured: false,
      banner: null,
      specs: {
        material: 'Brass',
        connectionType: 'Pull-type drain valve',
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // ΕΞΑΡΤΉΜΑΤΑ ΣΩΛΗΝΏΣΕΩΝ — ΑΝΤΙΣΤΆΣΕΙΣ ΣΩΛΉΝΑΣ
    // ═══════════════════════════════════════════════════════════════
    {
      name: 'Σωλήνα αέρος πλαστική 2x4mm',
      slug: 'solina-aeros-plastiki-2x4mm-pt010204',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'antistaseis-solinas',
      description:
        'Πλαστική σωλήνα αέρος 2x4mm. Κωδικός: PT-010204. Τιμή ανά μέτρο. Πολυαμίδιο PA12.',
      images: ['/images/products/010204/01.png'],
      price: 0.53,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 30,
      stock: 1000,
      isFeatured: false,
      banner: null,
      specs: {
        innerDiameter: '2mm',
        outerDiameter: '4mm',
        material: 'PA12 Polyamide',
      },
    },
    {
      name: 'Αντιστάσεις πλαστικής σωλήνας 2x4mm',
      slug: 'antistaseis-plastikis-solinas-2x4mm-it010204',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'antistaseis-solinas',
      description:
        'Πλαστική σφήνα (αντίσταση) για σωλήνα αέρος 2x4mm. Κωδικός: IT-010204. Πωλείται ανά τεμάχιο.',
      images: ['/images/products/010204/01.png'],
      price: 0.26,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 25,
      stock: 2000,
      isFeatured: false,
      banner: null,
      specs: {
        innerDiameter: '2mm',
        outerDiameter: '4mm',
        material: 'PA12 Polyamide',
      },
    },
    {
      name: 'Αντιστάσεις πλαστικής σωλήνας 4x6mm',
      slug: 'antistaseis-plastikis-solinas-4x6mm-it010406',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'antistaseis-solinas',
      description:
        'Πλαστική σφήνα για σωλήνα αέρος 4x6mm. Κωδικός: IT-010406. Η πιο δημοφιλής διάσταση.',
      images: ['/images/products/010406/01.png'],
      price: 0.26,
      brand: 'AVL',
      rating: 4.1,
      numReviews: 35,
      stock: 2500,
      isFeatured: false,
      banner: null,
      specs: {
        innerDiameter: '4mm',
        outerDiameter: '6mm',
        material: 'PA12 Polyamide',
      },
    },
    {
      name: 'Αντιστάσεις πλαστικής σωλήνας 5x8mm',
      slug: 'antistaseis-plastikis-solinas-5x8mm-it010508',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'antistaseis-solinas',
      description:
        'Πλαστική σφήνα για σωλήνα αέρος 5x8mm. Κωδικός: IT-010508.',
      images: ['/images/products/010508/01.png'],
      price: 0.28,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 18,
      stock: 1800,
      isFeatured: false,
      banner: null,
      specs: {
        innerDiameter: '5mm',
        outerDiameter: '8mm',
        material: 'PA12 Polyamide',
      },
    },
    {
      name: 'Αντιστάσεις πλαστικής σωλήνας 6x8mm',
      slug: 'antistaseis-plastikis-solinas-6x8mm-it010608',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'antistaseis-solinas',
      description:
        'Πλαστική σφήνα για σωλήνα αέρος 6x8mm. Κωδικός: IT-010608.',
      images: ['/images/products/010608/01.png'],
      price: 0.3,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 15,
      stock: 1500,
      isFeatured: false,
      banner: null,
      specs: {
        innerDiameter: '6mm',
        outerDiameter: '8mm',
        material: 'PA12 Polyamide',
      },
    },
    {
      name: 'Αντιστάσεις πλαστικής σωλήνας 8x10mm',
      slug: 'antistaseis-plastikis-solinas-8x10mm-it010810',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'antistaseis-solinas',
      description:
        'Πλαστική σφήνα για σωλήνα αέρος 8x10mm. Κωδικός: IT-010810.',
      images: ['/images/products/010810/01.png'],
      price: 0.35,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 12,
      stock: 1200,
      isFeatured: false,
      banner: null,
      specs: {
        innerDiameter: '8mm',
        outerDiameter: '10mm',
        material: 'PA12 Polyamide',
      },
    },
    {
      name: 'Αντιστάσεις πλαστικής σωλήνας 10x12mm',
      slug: 'antistaseis-plastikis-solinas-10x12mm-it011012',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'antistaseis-solinas',
      description:
        'Πλαστική σφήνα για σωλήνα αέρος 10x12mm. Κωδικός: IT-011012.',
      images: ['/images/placeholder.svg'],
      price: 0.4,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 10,
      stock: 1000,
      isFeatured: false,
      banner: null,
      specs: {
        innerDiameter: '10mm',
        outerDiameter: '12mm',
        material: 'PA12 Polyamide',
      },
    },
    {
      name: 'Αντιστάσεις πλαστικής σωλήνας 12x14mm',
      slug: 'antistaseis-plastikis-solinas-12x14mm-it011214',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'antistaseis-solinas',
      description:
        'Πλαστική σφήνα για σωλήνα αέρος 12x14mm. Κωδικός: IT-011214.',
      images: ['/images/placeholder.svg'],
      price: 0.45,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 8,
      stock: 800,
      isFeatured: false,
      banner: null,
      specs: {
        innerDiameter: '12mm',
        outerDiameter: '14mm',
        material: 'PA12 Polyamide',
      },
    },
    {
      name: 'Αντιστάσεις πλαστικής σωλήνας 14x18mm',
      slug: 'antistaseis-plastikis-solinas-14x18mm-it011418',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'antistaseis-solinas',
      description:
        'Πλαστική σφήνα για σωλήνα αέρος 14x18mm. Κωδικός: IT-011418. Η μεγαλύτερη διάσταση.',
      images: ['/images/products/011418/01.png'],
      price: 0.55,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 6,
      stock: 600,
      isFeatured: false,
      banner: null,
      specs: {
        innerDiameter: '14mm',
        outerDiameter: '18mm',
        material: 'PA12 Polyamide',
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // ΕΞΑΡΤΉΜΑΤΑ ΣΩΛΗΝΏΣΕΩΝ — ΟΎΡΈΣ, ΜΟΎΦΕΣ & ΤΆΠΕΣ
    // ═══════════════════════════════════════════════════════════════
    {
      name: 'Αρσενικά σιδηροσωλήνα M8/3mm',
      slug: 'arsenika-sidirossolina-m8-3mm-hb010803',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Αρσενικό σιδηροσωλήνας M8, σωλήνα 3mm. Κωδικός: HB010803. Γαλβανιζέ.',
      images: ['/images/products/010803/01.png'],
      price: 0.46,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 22,
      stock: 500,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: 'M8',
        material: 'Galvanized Steel',
        tubeSize: '3mm',
      },
    },
    {
      name: 'Τάπες φρένων M10',
      slug: 'tapes-frenon-m10-hb021001',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Τάπα υδραυλικών φρένων M10. Κωδικός: HB021001. Ορείχαλκος νικελαρισμένος.',
      images: ['/images/products/021001/01.png'],
      price: 0.57,
      brand: 'AVL',
      rating: 4.1,
      numReviews: 15,
      stock: 400,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: 'M10',
        material: 'Brass',
      },
    },
    {
      name: 'Μούφες θηλυκές M10',
      slug: 'moyfes-thylikes-m10-hb031001b',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Θηλυκή μούφα M10 για σωλήνες φρένων. Κωδικός: HB031001B. Ορείχαλκος.',
      images: ['/images/products/hb031001b/01.png'],
      price: 3.4,
      brand: 'AVL',
      rating: 4.3,
      numReviews: 11,
      stock: 200,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: 'M10',
        material: 'Brass',
      },
    },
    {
      name: 'Μούφες αρσενικό-θηλυκό M10',
      slug: 'moyfes-arseniko-thyliko-m10-hb061010',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Μούφα αρσενικό-θηλυκό M10. Κωδικός: HB061010. Για μετατροπή σπειρωμάτων.',
      images: ['/images/placeholder.svg'],
      price: 3.0,
      brand: 'AVL',
      rating: 4.2,
      numReviews: 9,
      stock: 180,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: 'M10',
        material: 'Brass',
      },
    },
    {
      name: 'Ουρές πλαστικής σωλήνας 6mm',
      slug: 'oyres-plastikis-solinas-6mm-hn010606',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Ουρά σύνδεσης πλαστικής σωλήνας 6mm. Κωδικός: HN010606. Ορείχαλκος.',
      images: ['/images/products/010606/01.png'],
      price: 1.32,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 14,
      stock: 300,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: '6mm',
        material: 'Brass',
      },
    },
    {
      name: 'Ουρές ελαστικής σωλήνας με λινά 10/6mm',
      slug: 'oyres-elastikis-solinas-lina-10-6mm-hn021006',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Ουρά για ελαστική σωλήνα με λινά 10mm/6mm. Κωδικός: HN021006.',
      images: ['/images/placeholder.svg'],
      price: 0.95,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 10,
      stock: 250,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: '10mm',
        material: 'Brass',
        tubeSize: '6mm',
      },
    },
    {
      name: 'Ουρές κομφλέρ ελαστικής σωλήνας 10/6mm',
      slug: 'oyres-komfler-elastikis-solinas-10-6mm-hn031006',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Ουρά κομφλέρ για ελαστική σωλήνα με λινά 10mm/6mm. Κωδικός: HN031006.',
      images: ['/images/products/031006/01.png'],
      price: 1.15,
      brand: 'AVL',
      rating: 4.1,
      numReviews: 8,
      stock: 200,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: '10mm',
        material: 'Brass',
        tubeSize: '6mm',
      },
    },
    {
      name: 'Συνδετικές ουρές πλαστικής σωλήνας 6/14mm',
      slug: 'syndetikes-oyres-plastikis-6-14mm-hn04614',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Συνδετική ουρά πλαστικής σωλήνας 6mm/14mm. Κωδικός: HN04614.',
      images: ['/images/products/hn04614/01.png'],
      price: 1.54,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 7,
      stock: 200,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: '14mm',
        material: 'Brass',
        tubeSize: '6mm',
      },
    },
    {
      name: 'Συστολικές ουρές πλαστικής σωλήνας 6/8mm',
      slug: 'systolikes-oyres-plastikis-6-8mm-hn050608',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Συστολική ουρά πλαστικής σωλήνας 6mm σε 8mm. Κωδικός: HN050608. Για αλλαγή διαμέτρου.',
      images: ['/images/products/050608/01.png'],
      price: 1.54,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 6,
      stock: 180,
      isFeatured: false,
      banner: null,
      specs: {
        material: 'Brass',
        tubeSize: '6mm to 8mm',
      },
    },
    {
      name: 'Ταφ πλαστικής σωλήνας 6/14mm',
      slug: 'taf-plastikis-solinas-6-14mm-hn060614',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Ταφ (T-piece) πλαστικής σωλήνας 6mm/14mm. Κωδικός: HN060614.',
      images: ['/images/products/060614/01.png'],
      price: 3.2,
      brand: 'AVL',
      rating: 4.2,
      numReviews: 5,
      stock: 150,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: '14mm',
        material: 'Brass',
        tubeSize: '6mm',
      },
    },
    {
      name: 'Αρσενικό βάσης με ουρά για πλαστική σωλήνα 12/6mm',
      slug: 'arseniko-vasis-oyra-plastiki-solina-12-6mm-hn141206',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Αρσενικό βάσης με ουρά για πλαστική σωλήνα 12mm, σπείρωμα 6mm. Κωδικός: HN141206.',
      images: ['/images/products/141206/01.png'],
      price: 2.29,
      brand: 'AVL',
      rating: 4.1,
      numReviews: 7,
      stock: 160,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: '12mm',
        material: 'Brass',
        tubeSize: '6mm',
      },
    },
    {
      name: 'Θηλυκά με ουρά κομφλέρ 18/38mm',
      slug: 'thylika-oyra-komfler-18-38mm-hn111838',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Θηλυκό με ουρά κομφλέρ 18mm/38mm. Κωδικός: HN111838. Για ελαστική σωλήνα.',
      images: ['/images/placeholder.svg'],
      price: 1.85,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 5,
      stock: 130,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: '18mm',
        material: 'Brass',
        tubeSize: '38mm',
      },
    },
    {
      name: 'Μούφες Αμερικής 22/12mm',
      slug: 'moyfes-amerikis-22-12mm-af052212',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Μούφα Αμερικής (flare fitting) 22mm/12mm. Κωδικός: AF052212. Χαλύβδινη γαλβανιζέ.',
      images: ['/images/products/052212/01.png'],
      price: 1.74,
      brand: 'AVL',
      rating: 4.2,
      numReviews: 8,
      stock: 120,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: '22mm',
        material: 'Galvanized Steel',
        tubeSize: '12mm',
      },
    },
    {
      name: 'Μούφες Αγγλίας 6/22mm',
      slug: 'moyfes-agglias-6-22mm-af030622',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Μούφα Αγγλίας (British fitting) 6mm/22mm. Κωδικός: AF030622. Ορείχαλκος.',
      images: ['/images/placeholder.svg'],
      price: 2.25,
      brand: 'AVL',
      rating: 4.1,
      numReviews: 6,
      stock: 100,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: '22mm',
        material: 'Brass',
        tubeSize: '6mm',
      },
    },
    {
      name: 'Τάπες αρσενικές M10',
      slug: 'tapes-arsenikes-m10-af061010',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Αρσενική τάπα M10. Κωδικός: AF061010. Ορείχαλκος νικελαρισμένος.',
      images: ['/images/placeholder.svg'],
      price: 0.68,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 12,
      stock: 350,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: 'M10',
        material: 'Brass',
      },
    },
    {
      name: 'Ροδέλες ορειχάλκου με O-Ring M12',
      slug: 'rodeles-oreixalkou-oring-m12-sr010012',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Ροδέλα ορειχάλκου με ενσωματωμένο O-Ring M12. Κωδικός: SR010012. Τέλεια στεγανοποίηση.',
      images: ['/images/placeholder.svg'],
      price: 0.4,
      brand: 'AVL',
      rating: 4.2,
      numReviews: 20,
      stock: 500,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: 'M12',
        material: 'Brass',
      },
    },
    {
      name: 'Ροδέλες αλουμινίου M6',
      slug: 'rodeles-alouminioy-m6-sr030006',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Ροδέλα αλουμινίου M6. Κωδικός: SR030006. Μαλακή, για στεγανοποίηση ρακόρ.',
      images: ['/images/products/030006/01.png'],
      price: 0.05,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 40,
      stock: 5000,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: 'M6',
        material: 'Aluminum',
      },
    },
    {
      name: 'Χαλκοροδέλες M6',
      slug: 'xalkorodeles-m6-sr040006',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Χαλκοροδέλα M6. Κωδικός: SR040006. Ανθεκτική σε υψηλές θερμοκρασίες.',
      images: ['/images/products/040006/01.png'],
      price: 0.1,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 35,
      stock: 5000,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: 'M6',
        material: 'Copper',
      },
    },
    {
      name: 'Μαστοί αέρος κομπλέ 22/22mm',
      slug: 'mastoi-aeros-komple-22-22mm-rf072222',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Μαστός αέρος κομπλέ 22mm/22mm. Κωδικός: RF072222. Ορείχαλκος, για σύνδεση σωληνώσεων αέρος.',
      images: ['/images/products/072222/01.png'],
      price: 6.6,
      brand: 'AVL',
      rating: 4.3,
      numReviews: 8,
      stock: 80,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: '22mm',
        material: 'Brass',
      },
    },
    {
      name: 'Μαστοί αέρος κομπλέ 26/26mm',
      slug: 'mastoi-aeros-komple-26-26mm-rf072626',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Μαστός αέρος κομπλέ 26mm/26mm. Κωδικός: RF072626. Ορείχαλκος.',
      images: ['/images/placeholder.svg'],
      price: 6.6,
      brand: 'AVL',
      rating: 4.2,
      numReviews: 6,
      stock: 70,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: '26mm',
        material: 'Brass',
      },
    },

    // ── Άκρα Volvo-Scania ─────────────────────────────────────────
    {
      name: 'Άκρο Volvo-Scania 17/38mm αρσενικό',
      slug: 'akro-volvo-scania-17-38mm-arseniko-hn131738m',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Άκρο σωλήνας ειδικό Volvo-Scania 17mm/38mm αρσενικό. Κωδικός: HN131738M. OEM αντικατάσταση.',
      images: ['/images/placeholder.svg'],
      price: 4.62,
      brand: 'AVL',
      rating: 4.5,
      numReviews: 10,
      stock: 60,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: '38mm',
        material: 'Brass',
        tubeSize: '17mm',
        compatibleVehicles: ['Volvo', 'Scania'],
      },
    },
    {
      name: 'Άκρο Volvo-Scania 07/14mm αρσενικό',
      slug: 'akro-volvo-scania-07-14mm-arseniko-hn130714m',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'oyres-moyfes-tapes',
      description:
        'Άκρο σωλήνας ειδικό Volvo-Scania 7mm/14mm αρσενικό. Κωδικός: HN130714M.',
      images: ['/images/placeholder.svg'],
      price: 4.62,
      brand: 'AVL',
      rating: 4.4,
      numReviews: 7,
      stock: 50,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: '14mm',
        material: 'Brass',
        tubeSize: '7mm',
        compatibleVehicles: ['Volvo', 'Scania'],
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // ΕΞΑΡΤΉΜΑΤΑ ΣΩΛΗΝΏΣΕΩΝ — ΣΩΛΉΝΕΣ & ΛΆΣΤΙΧΑ
    // ═══════════════════════════════════════════════════════════════
    {
      name: 'Σωλήνες μεταλλικές εύκαμπτες φρένων 3/16"',
      slug: 'solines-metallikes-eykamptes-frenon-3-16-ho1200316',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'solines-lastixa',
      description:
        'Μεταλλική εύκαμπτη σωλήνα φρένων 3/16". Κωδικός: HO-1200316. Τιμή ανά μέτρο. Πλεγμένη ατσάλινη.',
      images: ['/images/products/1200316/01.png'],
      price: 3.5,
      brand: 'AVL',
      rating: 4.4,
      numReviews: 14,
      stock: 500,
      isFeatured: false,
      banner: null,
      specs: {
        innerDiameter: '3/16"',
        material: 'Steel',
        maxPressure: '350 bar',
      },
    },
    {
      name: 'Σωλήνες R6 λαδιού 1/4"',
      slug: 'solines-r6-ladioy-1-4-ho060014',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'solines-lastixa',
      description:
        'Σωλήνα R6 λαδιού 1/4". Κωδικός: HO-060014. Τιμή ανά μέτρο. Ελαστική με πλέξη λινών.',
      images: ['/images/products/060014/01.png'],
      price: 4.66,
      brand: 'AVL',
      rating: 4.3,
      numReviews: 10,
      stock: 400,
      isFeatured: false,
      banner: null,
      specs: {
        innerDiameter: '1/4"',
        material: 'Rubber',
      },
    },
    {
      name: 'Σωλήνα Teflon σκληρή (1 σύρμα) 18mm',
      slug: 'solina-teflon-skliri-1-syrma-18mm-ho090018',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'solines-lastixa',
      description:
        'Σωλήνα Teflon σκληρή με 1 σύρμα ατσάλι 18mm. Κωδικός: HO-090018. Τιμή ανά μέτρο. Αντοχή σε θερμοκρασίες έως 260°C.',
      images: ['/images/products/090018/01.png'],
      price: 13.69,
      brand: 'AVL',
      rating: 4.6,
      numReviews: 7,
      stock: 200,
      isFeatured: false,
      banner: null,
      specs: {
        outerDiameter: '18mm',
        material: 'Teflon',
        maxPressure: '200 bar',
      },
    },
    {
      name: 'Σωλήνα Teflon εύκαμπτη 12mm',
      slug: 'solina-teflon-eykampti-12mm-ho080012',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'solines-lastixa',
      description:
        'Σωλήνα Teflon εύκαμπτη 12mm. Κωδικός: HO-080012. Τιμή ανά μέτρο. PTFE υψηλής καθαρότητας, ιδανική για υψηλές πιέσεις.',
      images: ['/images/placeholder.svg'],
      price: 80.62,
      brand: 'AVL',
      rating: 4.8,
      numReviews: 4,
      stock: 100,
      isFeatured: false,
      banner: null,
      specs: {
        outerDiameter: '12mm',
        material: 'Teflon',
        maxPressure: '300 bar',
      },
    },
    {
      name: 'Σωλήνα Flex πετρελαίου 6mm',
      slug: 'solina-flex-petrelaioy-6mm-ho010006',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'solines-lastixa',
      description:
        'Σωλήνα Flex πετρελαίου 6mm. Κωδικός: HO-010006. Τιμή ανά μέτρο. Ανθεκτική σε καύσιμα και λάδια.',
      images: ['/images/placeholder.svg'],
      price: 3.42,
      brand: 'AVL',
      rating: 4.2,
      numReviews: 12,
      stock: 300,
      isFeatured: false,
      banner: null,
      specs: {
        innerDiameter: '6mm',
        material: 'Rubber',
      },
    },
    {
      name: 'Σωλήνα Flex βενζίνης 32mm',
      slug: 'solina-flex-venzinis-32mm-ho020032',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'solines-lastixa',
      description:
        'Σωλήνα Flex βενζίνης 32mm. Κωδικός: HO-020032. Τιμή ανά μέτρο. Ανθεκτική στη βενζίνη και σε χημικά.',
      images: ['/images/placeholder.svg'],
      price: 6.03,
      brand: 'AVL',
      rating: 4.1,
      numReviews: 8,
      stock: 200,
      isFeatured: false,
      banner: null,
      specs: {
        innerDiameter: '32mm',
        material: 'Rubber',
      },
    },
    {
      name: 'Σωλήνα ελαστική R1 5mm',
      slug: 'solina-elastiki-r1-5mm-th01005',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'solines-lastixa',
      description:
        'Ελαστική σωλήνα R1 (1 πλέξη σύρματος) 5mm. Κωδικός: TH-01005. Τιμή ανά μέτρο. Πίεση λειτ. 250 bar.',
      images: ['/images/placeholder.svg'],
      price: 5.24,
      brand: 'AVL',
      rating: 4.3,
      numReviews: 9,
      stock: 250,
      isFeatured: false,
      banner: null,
      specs: {
        innerDiameter: '5mm',
        material: 'Rubber',
        maxPressure: '250 bar',
      },
    },
    {
      name: 'Σωλήνα ελαστική R2 6mm',
      slug: 'solina-elastiki-r2-6mm-th02006',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'solines-lastixa',
      description:
        'Ελαστική σωλήνα R2 (2 πλέξεις σύρματος) 6mm. Κωδικός: TH-02006. Τιμή ανά μέτρο. Πίεση λειτ. 400 bar.',
      images: ['/images/placeholder.svg'],
      price: 6.36,
      brand: 'AVL',
      rating: 4.4,
      numReviews: 6,
      stock: 200,
      isFeatured: false,
      banner: null,
      specs: {
        innerDiameter: '6mm',
        material: 'Rubber',
        maxPressure: '400 bar',
      },
    },
    {
      name: 'Κυλινδρικοί σύνδεσμοι βάσης 6/10mm',
      slug: 'kylindriko-syndesmoi-vasis-6-10mm-df010610',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'solines-lastixa',
      description:
        'Κυλινδρικός σύνδεσμος βάσης 6mm/10mm. Κωδικός: DF-010610. Ατσάλι γαλβανιζέ.',
      images: ['/images/products/010610/01.png'],
      price: 1.15,
      brand: 'AVL',
      rating: 4.0,
      numReviews: 8,
      stock: 200,
      isFeatured: false,
      banner: null,
      specs: {
        threadSize: '6mm/10mm',
        material: 'Galvanized Steel',
      },
    },
    {
      name: 'Ταφ αναμονών σκέτο',
      slug: 'taf-anamonon-sketo-tp020001',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'solines-lastixa',
      description:
        'Ταφ αναμονών σκέτο (χωρίς βαλβίδα). Κωδικός: TP020001. Χαλύβδινο γαλβανιζέ.',
      images: ['/images/products/020001/01.png'],
      price: 8.4,
      brand: 'AVL',
      rating: 4.3,
      numReviews: 5,
      stock: 60,
      isFeatured: false,
      banner: null,
      specs: {
        material: 'Galvanized Steel',
        connectionType: 'T-piece standpipe',
      },
    },
    {
      name: 'Προεκτάσεις ρεγουλατόρων MAN',
      slug: 'proektaseis-regoulatoron-man-sf050893',
      category: 'Εξαρτήματα Σωληνώσεων / Ρακόρ',
      categorySlug: 'solines-lastixa',
      description:
        'Προέκταση ρεγουλατόρου ειδική MAN. Κωδικός: SF050893. Για ρεγουλατόρες φρένων MAN.',
      images: ['/images/placeholder.svg'],
      price: 3.8,
      brand: 'AVL',
      rating: 4.1,
      numReviews: 4,
      stock: 40,
      isFeatured: false,
      banner: null,
      specs: {
        material: 'Steel',
        compatibleVehicles: ['MAN'],
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // ΚΑΤΑΣΚΕΥΈΣ ΣΩΛΉΝΩΝ — ΜΑΡΚΟΎΤΣΙΑ TEFLON
    // ═══════════════════════════════════════════════════════════════
    {
      name: 'Μαρκούτσι Teflon σκληρό ημιεύκαμπτο 0.55m',
      slug: 'markoutsi-teflon-skliro-imieykampto-055m-th010157',
      category: 'Κατασκευές Σωλήνων / Μαρκούτσια',
      categorySlug: 'markoutsia-teflon',
      description:
        'Έτοιμο μαρκούτσι Teflon σκληρό ημιεύκαμπτο 0.55m με πρεσσαριστά άκρα. Κωδικός: TH010157. Αντοχή σε θερμοκρασίες -60°C έως +260°C.',
      images: ['/images/products/010157/01.png'],
      price: 35.0,
      brand: 'AVL',
      rating: 4.7,
      numReviews: 8,
      stock: 30,
      isFeatured: false,
      banner: null,
      specs: {
        material: 'Teflon',
        length: '0.55m',
        tempRange: '-60°C to +260°C',
      },
    },
    {
      name: 'Μαρκούτσι Teflon εύκαμπτο 0.36m',
      slug: 'markoutsi-teflon-eykampto-036m-th010157f',
      category: 'Κατασκευές Σωλήνων / Μαρκούτσια',
      categorySlug: 'markoutsia-teflon',
      description:
        'Έτοιμο μαρκούτσι Teflon εύκαμπτο 0.36m. PTFE εύκαμπτο με ανοξείδωτο πλέγμα. Ιδανικό για στενούς χώρους.',
      images: ['/images/placeholder.svg'],
      price: 42.0,
      brand: 'AVL',
      rating: 4.6,
      numReviews: 5,
      stock: 25,
      isFeatured: false,
      banner: null,
      specs: {
        material: 'Teflon',
        length: '0.36m',
        tempRange: '-60°C to +260°C',
      },
    },
    {
      name: 'Μαρκούτσια Actros-Atego με κούμπωμα ασφαλείας 2.40m',
      slug: 'markoutsia-actros-atego-koumpoma-asfaleias-240m-th030240',
      category: 'Κατασκευές Σωλήνων / Μαρκούτσια',
      categorySlug: 'markoutsia-teflon',
      description:
        'Μαρκούτσι ειδικό για Mercedes Actros και Atego με κούμπωμα ασφαλείας 2.40m. Κωδικός: TH030240. Quick-connect σύστημα.',
      images: ['/images/placeholder.svg'],
      price: 85.0,
      brand: 'AVL',
      rating: 4.8,
      numReviews: 6,
      stock: 15,
      isFeatured: false,
      banner: null,
      specs: {
        material: 'Teflon',
        length: '2.40m',
        compatibleVehicles: ['Mercedes Actros', 'Mercedes Atego'],
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // ΚΑΤΑΣΚΕΥΈΣ ΣΩΛΉΝΩΝ — ΜΑΡΚΟΎΤΣΙΑ ΦΡΈΝΩΝ
    // ═══════════════════════════════════════════════════════════════
    {
      name: 'Μαρκούτσια φρένων - αμπραγιάζ 0.45m',
      slug: 'markoutsia-frenon-amprgiaz-045m-th040145',
      category: 'Κατασκευές Σωλήνων / Μαρκούτσια',
      categorySlug: 'markoutsia-frenon',
      description:
        'Έτοιμο μαρκούτσι υδραυλικών φρένων και αμπραγιάζ 0.45m. Κωδικός: TH040145. Πρεσσαριστά άκρα, DOT4 συμβατό.',
      images: ['/images/placeholder.svg'],
      price: 18.0,
      brand: 'AVL',
      rating: 4.5,
      numReviews: 12,
      stock: 40,
      isFeatured: false,
      banner: null,
      specs: {
        material: 'Rubber',
        length: '0.45m',
        maxPressure: '200 bar',
      },
    },
    {
      name: 'Μαρκούτσια γρασσαδόρου 0.30m',
      slug: 'markoutsia-grassadorou-030m-th040430',
      category: 'Κατασκευές Σωλήνων / Μαρκούτσια',
      categorySlug: 'markoutsia-frenon',
      description:
        'Μαρκούτσι γρασσαδόρου 0.30m. Κωδικός: TH040430. Υψηλής πίεσης, για γρασσαδόρους χειρός και πνευματικούς.',
      images: ['/images/placeholder.svg'],
      price: 15.0,
      brand: 'AVL',
      rating: 4.3,
      numReviews: 9,
      stock: 35,
      isFeatured: false,
      banner: null,
      specs: {
        material: 'Rubber',
        length: '0.30m',
        maxPressure: '400 bar',
      },
    },
    {
      name: 'Μαρκούτσια αυτόματης λίπανσης 1.00m',
      slug: 'markoutsia-aytomatis-lipansis-100m-th153261',
      category: 'Κατασκευές Σωλήνων / Μαρκούτσια',
      categorySlug: 'markoutsia-frenon',
      description:
        'Μαρκούτσι για σύστημα αυτόματης λίπανσης 1.00m. Κωδικός: TH153261. Ειδικό εύκαμπτο υλικό ανθεκτικό σε γράσο.',
      images: ['/images/placeholder.svg'],
      price: 28.0,
      brand: 'AVL',
      rating: 4.4,
      numReviews: 4,
      stock: 20,
      isFeatured: false,
      banner: null,
      specs: {
        material: 'Nylon',
        length: '1.00m',
      },
    },
    {
      name: 'Σύνδεσμοι φρένων Volvo',
      slug: 'syndesmoi-frenon-volvo-sf070018',
      category: 'Κατασκευές Σωλήνων / Μαρκούτσια',
      categorySlug: 'markoutsia-frenon',
      description:
        'Σύνδεσμος φρένων ειδικός Volvo. Κωδικός: SF-070018. OEM αντικατάσταση, πρεσσαρισμένος.',
      images: ['/images/products/070018/01.png'],
      price: 2.77,
      brand: 'AVL',
      rating: 4.2,
      numReviews: 7,
      stock: 50,
      isFeatured: false,
      banner: null,
      specs: {
        material: 'Steel',
        compatibleVehicles: ['Volvo'],
      },
    },
  ],

  users: [
    {
      name: 'Βασίλειος Λεμοντζόγλου',
      email: 'admin@avl.gr',
      role: 'admin',
      password: hashSync('admin123', 10),
    },
    {
      name: 'Γιώργος Καρακατσάνης',
      email: 'gkarakatsanis@avl.gr',
      role: 'admin',
      password: hashSync('admin123', 10),
    },
    {
      name: 'Νίκος Παπαδόπουλος',
      email: 'n.papadopoulos@gmail.com',
      role: 'user',
      password: hashSync('password', 10),
    },
    {
      name: 'Μαρία Αντωνίου',
      email: 'm.antoniou@gmail.com',
      role: 'user',
      password: hashSync('password', 10),
    },
    {
      name: 'Δημήτρης Κωστόπουλος',
      email: 'd.kostopoulos@yahoo.gr',
      role: 'user',
      password: hashSync('password', 10),
    },
    {
      name: 'Ελένη Γεωργίου',
      email: 'e.georgiou@hotmail.com',
      role: 'user',
      password: hashSync('password', 10),
    },
  ],

  reviews: [
    // ── Νίκος Παπαδόπουλος ──────────────────────────────────────
    {
      userEmail: 'n.papadopoulos@gmail.com',
      productSlug: 'granazi-abs-100-mercedes-actros',
      rating: 5,
      title: 'Εξαιρετική ποιότητα',
      description:
        'Άψογη εφαρμογή στο Actros MP3. Τοποθετήθηκε χωρίς κανένα πρόβλημα, ο αισθητήρας ABS δουλεύει τέλεια.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'n.papadopoulos@gmail.com',
      productSlug: 'fysoynes-de-tampouro-t24-fa1034a',
      rating: 4,
      title: 'Πολύ καλό προϊόν',
      description:
        'Σωστές διαστάσεις, καλή ποιότητα κατασκευής. Μόνο η συσκευασία θα μπορούσε να ήταν καλύτερη.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'n.papadopoulos@gmail.com',
      productSlug: 'rakor-pressarista-3-16-r1at-hb041001ae',
      rating: 5,
      title: 'Ακριβώς αυτό που χρειαζόμουν',
      description:
        'Τέλεια ρακόρ, σφραγίζουν άψογα. Τα χρησιμοποιώ σε όλο τον στόλο μου.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'n.papadopoulos@gmail.com',
      productSlug: 'markoutsia-actros-atego-koumpoma-asfaleias-240m-th030240',
      rating: 5,
      title: 'Κορυφαίο μαρκούτσι',
      description:
        'Ανθεκτικό, σωστό μήκος, κούμπωμα ασφαλείας λειτουργεί τέλεια. Συνιστώ ανεπιφύλακτα.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'n.papadopoulos@gmail.com',
      productSlug: 'solina-teflon-skliri-1-syrma-18mm-ho090018',
      rating: 4,
      title: 'Πολύ ανθεκτική σωλήνα',
      description:
        'Η σωλήνα Teflon είναι εξαιρετικής ποιότητας. Αντέχει σε υψηλές θερμοκρασίες.',
      isVerifiedPurchase: true,
    },

    // ── Μαρία Αντωνίου ──────────────────────────────────────────
    {
      userEmail: 'm.antoniou@gmail.com',
      productSlug: 'granazi-abs-48-daf-cf-xf',
      rating: 4,
      title: 'Σωστή εφαρμογή',
      description:
        'Μπήκε στο DAF CF χωρίς πρόβλημα. Η ποιότητα κατασκευής είναι πολύ καλή.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'm.antoniou@gmail.com',
      productSlug: 'granazi-abs-100-volvo-fh-fm',
      rating: 5,
      title: 'Άριστη ποιότητα',
      description:
        'Τέλεια εφαρμογή στο Volvo FH. Premium ποιότητα, αξίζει κάθε ευρώ.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'm.antoniou@gmail.com',
      productSlug: 'fysoynes-me-tampouro-t12-fa1012a',
      rating: 4,
      title: 'Καλή φυσούνα',
      description:
        'Λειτουργεί κανονικά, σωστές διαστάσεις. Τοποθέτηση εύκολη.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'm.antoniou@gmail.com',
      productSlug: 'mproutzino-daxtylidi-thalamou-cnc',
      rating: 5,
      title: 'Τέλεια κατεργασία CNC',
      description:
        'Ακριβής κατασκευή, ανθεκτικό υλικό. Ιδανικό ανταλλακτικό.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'm.antoniou@gmail.com',
      productSlug: 'taf-ydravlikon-frenon-hb051001b',
      rating: 3,
      title: 'Μέτριο',
      description:
        'Κάνει τη δουλειά του αλλά η ποιότητα του φινιρίσματος δεν με ενθουσίασε.',
      isVerifiedPurchase: true,
    },

    // ── Δημήτρης Κωστόπουλος ─────────────────────────────────────
    {
      userEmail: 'd.kostopoulos@yahoo.gr',
      productSlug: 'granazi-abs-90-mercedes-atego',
      rating: 5,
      title: 'Άμεση παράδοση',
      description:
        'Παράγγειλα και το είχα την επόμενη μέρα. Εφαρμογή τέλεια στο Atego.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'd.kostopoulos@yahoo.gr',
      productSlug: 'atsalinos-axonas-frenon-cnc',
      rating: 4,
      title: 'Πολύ καλή κατεργασία',
      description:
        'Ο ατσάλινος άξονας είναι ακριβής στις διαστάσεις. Πολύ καλή δουλειά.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'd.kostopoulos@yahoo.gr',
      productSlug: 'fysoynes-de-diskofrenoy-t16-24-fa1065b',
      rating: 5,
      title: 'Εξαιρετικές φυσούνες',
      description:
        'Δουλεύουν τέλεια στα δισκόφρενα. Πολύ ανθεκτικές, αξίζουν τα λεφτά τους.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'd.kostopoulos@yahoo.gr',
      productSlug: 'markoutsi-teflon-skliro-imieykampto-055m-th010157',
      rating: 4,
      title: 'Αξιόπιστο μαρκούτσι',
      description:
        'Σωστό μήκος, ανθεκτικό στη θερμοκρασία. Καλή σχέση ποιότητας-τιμής.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'd.kostopoulos@yahoo.gr',
      productSlug: 'syndesmos-plastikos-aytomatos-ypsilon-pp12304',
      rating: 3,
      title: 'Ικανοποιητικό',
      description:
        'Λειτουργεί σωστά αλλά ο πλαστικός σύνδεσμος θέλει προσοχή στο σφίξιμο.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'd.kostopoulos@yahoo.gr',
      productSlug: 'eksaerotires-frenon-m6-hb080601',
      rating: 4,
      title: 'Κάνουν τη δουλειά τους',
      description:
        'Σωστοί εξαερωτήρες, αξιόπιστοι. Τους αλλάζω σε κάθε service.',
      isVerifiedPurchase: true,
    },

    // ── Ελένη Γεωργίου ──────────────────────────────────────────
    {
      userEmail: 'e.georgiou@hotmail.com',
      productSlug: 'granazi-abs-80-man-tgx',
      rating: 5,
      title: 'Εξαιρετικό γρανάζι',
      description:
        'Τοποθετήθηκε στο MAN TGX χωρίς πρόβλημα. Εξαιρετική ποιότητα κατασκευής.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'e.georgiou@hotmail.com',
      productSlug: 'vasi-stirixis-dagkanas-cnc',
      rating: 4,
      title: 'Πολύ καλή βάση',
      description:
        'Ακριβής κατεργασία CNC, εφαρμόζει τέλεια. Ανθεκτικό υλικό.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'e.georgiou@hotmail.com',
      productSlug: 'fysoynes-me-diskofrenoy-fa1021b',
      rating: 5,
      title: 'Αξίζει κάθε ευρώ',
      description:
        'Η φυσούνα δισκόφρενου λειτουργεί τέλεια. Πολύ καλή απόδοση.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'e.georgiou@hotmail.com',
      productSlug: 'markoutsia-frenon-amprgiaz-045m-th040145',
      rating: 4,
      title: 'Αξιόπιστο ανταλλακτικό',
      description:
        'Σωστές διαστάσεις, ανθεκτικό υλικό. Το χρησιμοποιώ στο συνεργείο μου.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'e.georgiou@hotmail.com',
      productSlug: 'valvida-kazanioy-bk22',
      rating: 3,
      title: 'Μέτρια ποιότητα',
      description:
        'Λειτουργεί αλλά η κατασκευή δεν είναι στο ίδιο επίπεδο με τα υπόλοιπα.',
      isVerifiedPurchase: true,
    },
    {
      userEmail: 'e.georgiou@hotmail.com',
      productSlug: 'solina-flex-petrelaioy-6mm-ho010006',
      rating: 5,
      title: 'Τέλεια σωλήνα',
      description:
        'Πολύ ανθεκτική σωλήνα, ιδανική για πετρέλαιο. Εύκαμπτη και ανθεκτική.',
      isVerifiedPurchase: true,
    },
  ],

  orders: [
    // ── Παραγγελία 1: Delivered + Paid ───────────────────────────
    {
      userEmail: 'n.papadopoulos@gmail.com',
      status: 'delivered',
      isPaid: true,
      paidAt: new Date('2026-01-15T10:30:00'),
      isDelivered: true,
      deliveredAt: new Date('2026-01-18T14:00:00'),
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Νίκος Παπαδόπουλος',
        address: 'Λεωφ. Αθηνών 125',
        city: 'Αθήνα',
        postalCode: '10447',
        country: 'Ελλάδα',
        phone: '2101234567',
      },
      createdAt: new Date('2026-01-14T09:00:00'),
      items: [
        {
          productSlug: 'granazi-abs-100-mercedes-actros',
          qty: 2,
          price: 62.0,
        },
        {
          productSlug: 'fysoynes-de-tampouro-t24-fa1034a',
          qty: 4,
          price: 12.0,
        },
      ],
    },
    // ── Παραγγελία 2: Shipped + Paid ─────────────────────────────
    {
      userEmail: 'n.papadopoulos@gmail.com',
      status: 'shipped',
      isPaid: true,
      paidAt: new Date('2026-02-20T11:00:00'),
      isDelivered: false,
      deliveredAt: null,
      paymentMethod: 'PayPal',
      shippingAddress: {
        fullName: 'Νίκος Παπαδόπουλος',
        address: 'Λεωφ. Αθηνών 125',
        city: 'Αθήνα',
        postalCode: '10447',
        country: 'Ελλάδα',
        phone: '2101234567',
      },
      createdAt: new Date('2026-02-20T08:30:00'),
      items: [
        {
          productSlug: 'markoutsia-actros-atego-koumpoma-asfaleias-240m-th030240',
          qty: 1,
          price: 85.0,
        },
        {
          productSlug: 'solina-teflon-skliri-1-syrma-18mm-ho090018',
          qty: 2,
          price: 13.69,
        },
        {
          productSlug: 'rakor-pressarista-3-16-r1at-hb041001ae',
          qty: 10,
          price: 3.0,
        },
      ],
    },
    // ── Παραγγελία 3: Delivered + Paid ───────────────────────────
    {
      userEmail: 'm.antoniou@gmail.com',
      status: 'delivered',
      isPaid: true,
      paidAt: new Date('2026-01-05T09:15:00'),
      isDelivered: true,
      deliveredAt: new Date('2026-01-08T11:30:00'),
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Μαρία Αντωνίου',
        address: 'Τσιμισκή 42',
        city: 'Θεσσαλονίκη',
        postalCode: '54623',
        country: 'Ελλάδα',
        phone: '2310567890',
      },
      createdAt: new Date('2026-01-04T14:00:00'),
      items: [
        {
          productSlug: 'granazi-abs-48-daf-cf-xf',
          qty: 1,
          price: 45.0,
        },
        {
          productSlug: 'granazi-abs-100-volvo-fh-fm',
          qty: 1,
          price: 65.0,
        },
        {
          productSlug: 'fysoynes-me-tampouro-t12-fa1012a',
          qty: 2,
          price: 8.5,
        },
        {
          productSlug: 'mproutzino-daxtylidi-thalamou-cnc',
          qty: 1,
          price: 35.0,
        },
      ],
    },
    // ── Παραγγελία 4: Processing + Paid ──────────────────────────
    {
      userEmail: 'm.antoniou@gmail.com',
      status: 'processing',
      isPaid: true,
      paidAt: new Date('2026-03-08T16:45:00'),
      isDelivered: false,
      deliveredAt: null,
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Μαρία Αντωνίου',
        address: 'Τσιμισκή 42',
        city: 'Θεσσαλονίκη',
        postalCode: '54623',
        country: 'Ελλάδα',
        phone: '2310567890',
      },
      createdAt: new Date('2026-03-08T16:30:00'),
      items: [
        {
          productSlug: 'taf-ydravlikon-frenon-hb051001b',
          qty: 3,
          price: 7.75,
        },
        {
          productSlug: 'eksaerotires-frenon-m6-hb080601',
          qty: 6,
          price: 1.4,
        },
      ],
    },
    // ── Παραγγελία 5: Delivered + Paid (CashOnDelivery) ──────────
    {
      userEmail: 'd.kostopoulos@yahoo.gr',
      status: 'delivered',
      isPaid: true,
      paidAt: new Date('2026-02-05T12:00:00'),
      isDelivered: true,
      deliveredAt: new Date('2026-02-05T12:00:00'),
      paymentMethod: 'CashOnDelivery',
      shippingAddress: {
        fullName: 'Δημήτρης Κωστόπουλος',
        address: 'Ηρώων Πολυτεχνείου 18',
        city: 'Πειραιάς',
        postalCode: '18535',
        country: 'Ελλάδα',
        phone: '2104567890',
      },
      createdAt: new Date('2026-02-02T10:00:00'),
      items: [
        {
          productSlug: 'granazi-abs-90-mercedes-atego',
          qty: 1,
          price: 55.0,
        },
        {
          productSlug: 'atsalinos-axonas-frenon-cnc',
          qty: 1,
          price: 85.0,
        },
        {
          productSlug: 'fysoynes-de-diskofrenoy-t16-24-fa1065b',
          qty: 2,
          price: 14.0,
        },
      ],
    },
    // ── Παραγγελία 6: Shipped + Paid ─────────────────────────────
    {
      userEmail: 'd.kostopoulos@yahoo.gr',
      status: 'shipped',
      isPaid: true,
      paidAt: new Date('2026-03-01T14:20:00'),
      isDelivered: false,
      deliveredAt: null,
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Δημήτρης Κωστόπουλος',
        address: 'Ηρώων Πολυτεχνείου 18',
        city: 'Πειραιάς',
        postalCode: '18535',
        country: 'Ελλάδα',
        phone: '2104567890',
      },
      createdAt: new Date('2026-03-01T13:00:00'),
      items: [
        {
          productSlug: 'markoutsi-teflon-skliro-imieykampto-055m-th010157',
          qty: 3,
          price: 35.0,
        },
        {
          productSlug: 'syndesmos-plastikos-aytomatos-ypsilon-pp12304',
          qty: 10,
          price: 0.62,
        },
      ],
    },
    // ── Παραγγελία 7: Pending + Not Paid ─────────────────────────
    {
      userEmail: 'e.georgiou@hotmail.com',
      status: 'pending',
      isPaid: false,
      paidAt: null,
      isDelivered: false,
      deliveredAt: null,
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Ελένη Γεωργίου',
        address: 'Αργοναυτών 7',
        city: 'Βόλος',
        postalCode: '38221',
        country: 'Ελλάδα',
        phone: '2421098765',
      },
      createdAt: new Date('2026-03-09T18:00:00'),
      items: [
        {
          productSlug: 'granazi-abs-80-man-tgx',
          qty: 1,
          price: 58.0,
        },
        {
          productSlug: 'vasi-stirixis-dagkanas-cnc',
          qty: 1,
          price: 95.0,
        },
      ],
    },
    // ── Παραγγελία 8: Delivered + Paid ───────────────────────────
    {
      userEmail: 'e.georgiou@hotmail.com',
      status: 'delivered',
      isPaid: true,
      paidAt: new Date('2026-01-22T08:00:00'),
      isDelivered: true,
      deliveredAt: new Date('2026-01-25T10:30:00'),
      paymentMethod: 'PayPal',
      shippingAddress: {
        fullName: 'Ελένη Γεωργίου',
        address: 'Αργοναυτών 7',
        city: 'Βόλος',
        postalCode: '38221',
        country: 'Ελλάδα',
        phone: '2421098765',
      },
      createdAt: new Date('2026-01-21T15:00:00'),
      items: [
        {
          productSlug: 'fysoynes-me-diskofrenoy-fa1021b',
          qty: 4,
          price: 10.5,
        },
        {
          productSlug: 'markoutsia-frenon-amprgiaz-045m-th040145',
          qty: 2,
          price: 18.0,
        },
        {
          productSlug: 'valvida-kazanioy-bk22',
          qty: 3,
          price: 3.88,
        },
      ],
    },
    // ── Παραγγελία 9: Processing + Paid ──────────────────────────
    {
      userEmail: 'e.georgiou@hotmail.com',
      status: 'processing',
      isPaid: true,
      paidAt: new Date('2026-03-05T10:15:00'),
      isDelivered: false,
      deliveredAt: null,
      paymentMethod: 'CashOnDelivery',
      shippingAddress: {
        fullName: 'Ελένη Γεωργίου',
        address: 'Αργοναυτών 7',
        city: 'Βόλος',
        postalCode: '38221',
        country: 'Ελλάδα',
        phone: '2421098765',
      },
      createdAt: new Date('2026-03-04T09:30:00'),
      items: [
        {
          productSlug: 'solina-flex-petrelaioy-6mm-ho010006',
          qty: 2,
          price: 3.42,
        },
        {
          productSlug: 'eksaerotires-frenon-m6-hb080601',
          qty: 10,
          price: 1.4,
        },
      ],
    },
    // ── Παραγγελία 10: Pending + Not Paid ────────────────────────
    {
      userEmail: 'n.papadopoulos@gmail.com',
      status: 'pending',
      isPaid: false,
      paidAt: null,
      isDelivered: false,
      deliveredAt: null,
      paymentMethod: 'PayPal',
      shippingAddress: {
        fullName: 'Νίκος Παπαδόπουλος',
        address: 'Λεωφ. Αθηνών 125',
        city: 'Αθήνα',
        postalCode: '10447',
        country: 'Ελλάδα',
        phone: '2101234567',
      },
      createdAt: new Date('2026-03-10T07:00:00'),
      items: [
        {
          productSlug: 'flantza-syndesis-kompreser-cnc',
          qty: 1,
          price: 110.0,
        },
      ],
    },
  ],

  coupons: [
    {
      code: 'WELCOME10',
      description: '10% έκπτωση για νέους πελάτες',
      discountType: 'percentage',
      discountValue: 10,
      minOrderAmount: 50,
      maxDiscount: 50,
      maxUses: null,
      maxUsesPerUser: 1,
      validFrom: new Date('2026-01-01'),
      validUntil: new Date('2026-12-31'),
      isActive: true,
      appliesToAll: true,
    },
    {
      code: 'SUMMER2026',
      description: '15% καλοκαιρινή έκπτωση',
      discountType: 'percentage',
      discountValue: 15,
      minOrderAmount: 80,
      maxDiscount: 100,
      maxUses: 200,
      maxUsesPerUser: 2,
      validFrom: new Date('2026-06-01'),
      validUntil: new Date('2026-08-31'),
      isActive: true,
      appliesToAll: true,
    },
    {
      code: 'FREESHIP',
      description: 'Δωρεάν αποστολή για παραγγελίες άνω των 100€',
      discountType: 'free_shipping',
      discountValue: 0,
      minOrderAmount: 100,
      maxDiscount: null,
      maxUses: null,
      maxUsesPerUser: 5,
      validFrom: new Date('2026-01-01'),
      validUntil: new Date('2026-12-31'),
      isActive: true,
      appliesToAll: true,
    },
    {
      code: 'FLEET20',
      description: '20% έκπτωση για στόλους — ελάχιστη παραγγελία 200€',
      discountType: 'percentage',
      discountValue: 20,
      minOrderAmount: 200,
      maxDiscount: 300,
      maxUses: 50,
      maxUsesPerUser: 10,
      validFrom: new Date('2026-01-01'),
      validUntil: new Date('2027-01-01'),
      isActive: true,
      appliesToAll: true,
    },
  ],
}

export default sampleData
